#!/usr/bin/env bash
#Display the string "To infinity and beyond" infinitely. With:
# sleep 2 in between each iteration
# I am invincible!!! when receiving a SIGTERM signal
trap 'echo "I am invincible!!!"' SIGTERM
until false;
do
       echo "To infinity and beyond"
       sleep 2
done
