#!/usr/bin/env bash
# Script that displays numbers from 1-100. Moreso, displays:
#   "FizzBuzz" for multiple of 3 & 5
#   "Fizz" for multiple of 3
#   "Buzz" for multiple of 5
# Else display numbers in a list format.

for i in {1..100}; do
      if (( i % 3 == 0 && i % 5 == 0 )); then
      	 echo "FizzBuzz"
      elif (( i % 3 == 0 )); then
      	 echo "Fizz"
      elif (( i % 5 == 0 )); then
         echo "Buzz"
      else
          echo "$i"
      fi
done
