#!/usr/bin/env bash
#Displays some lines of the content of a file in a story-like manner.
file_name="/etc/passwd"
while IFS=: read -r uname pass uid gid uidinfo home shell; do
      echo "The user $uname is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $pass, more info about the user here: $uidinfo"
done < "$file_name"
