#!/usr/bin/env bash
# display Best School" 9 times and after 9th iteration display "Hi"

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done
